const productos = [
    {
        id: 1,
        codigo: "Nat0010",
        nombre: "Kit Tododia Algodón",
        descripcion: "Crema hidratante 400 ml + Body Splash 200 ml",
        categoria: "Tododia",
        subcategoria:"Cremas",
        precio: 31900,
        imagen: "img/algodon.jpeg",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 2,
        codigo: "Nat0010",
        nombre: "Kit Tododia Acerola",
        descripcion: "Crema hidratante + Body Splash",
        categoria: "Tododia",
        subcategoria:"Cremas",
        precio: 31900,
        imagen: "img/acerola.jpeg",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 3,
        nombre: "Pitanga Preta",
        descripcion: "Perfume Ekos 150 ml",
        categoria: "Perfumes",
        subcategoria:"Ekos",
        precio: 30000,
        imagen: "img/pitanga.jpeg",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 4,
        nombre: "Kit Humor Rojo",
        descripcion: "Labial + Esmalte + Perfume",
        categoria: "Maquillaje",
        subcategoria:"Humor",
        precio: 20000,
        imagen: "img/humor.png",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 5,
        nombre: "Frescor Ekos Ishpink",
        codigo: "Nat0013",
        descripción: "Frescor Ekos Ishpink destaca por su aroma fresco y sofisticado con delicadas notas florales y amaderadas. Una fragancia elegante que expresa la riqueza y autenticidad de la naturaleza brasileña.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precio: 20000,
        imagen: "img/Frescor Ekos Ishpink.jpeg",
        imagen2: "img/Frescor Ekos Ishpink2.jpeg",
        oferta: false,
        destacado: true,
        stock: 3
    },
     {
        id: 6,
        nombre: "Frescor Ekos Tucuma",
        codigo: "Nat0013",
        descripción: "Frescor Ekos Tucumã combina notas frescas y cremosas inspiradas en la biodiversidad amazónica. Una fragancia moderna, envolvente y llena de vitalidad para acompañarte todos los días.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precio: 20000,
        imagen: "img/Frescor Ekos Tucuma.jpeg",
        imagen2: "img/Frescor Ekos Tucuma2.jpeg",
        oferta: false,
        destacado: true,
        stock: 1
    },
    {
        id: 7,
        codigo: "Nat0002",
        nombre: "Kaiak Clasico",
        descripcion: "Kaiak Clásico Masculino combina notas cítricas, aromáticas y acuáticas para ofrecer una fragancia fresca, versátil y perfecta para el uso diario.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/kaiak.jpg",
        imagen2: "img/kaiak2.jpg",
        oferta: true,
        destacado: true,
        stock: 4
    },
     {
        id: 8,
        codigo: "Nat0002",
        nombre: "Kaiak Oceano",
        descripcion: "Kaiak Oceano Masculino está inspirado en la fuerza y frescura del mar. Un perfume revitalizante ideal para hombres activos.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/kaiak oceano.jpeg",
        imagen2: "img/kaiak oceano2.jpeg",
        oferta: true,
        destacado: true,
        stock: 4
    },
    {
        id: 9,
        nombre: "Frescor Ekos Acai",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Açaí ofrece una fragancia ligera y refrescante con notas frutales inspiradas en la riqueza de la biodiversidad brasileña.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precio: 20000,
        imagen: "img/Frescor Ekos Acai2.jpeg",
        imagen2: "img/Frescor Ekos Acai.jpeg",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 10,
        nombre: "Frescor Ekos Maracuya",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Maracuyá combina un aroma tropical y fresco que transmite energía, alegría y bienestar durante todo el día.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precio: 20000,
        imagen: "img/Frescor Ekos Mara2.jpeg",
        imagen2: "img/Frescor Ekos Mara.jpeg",
        oferta: false,
        destacado: true,
        stock: 4
    },
    {
        id: 11,
        nombre: "Frescor Ekos Cacau",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Cacau presenta una fragancia cálida y envolvente inspirada en el cacao brasileño, ideal para quienes buscan un aroma con personalidad.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/Frescor Ekos Cacau.jpeg",
        imagen2: "img/Frescor Ekos Cacau2.jpeg",
        oferta: true,
        destacado: true,
        stock: 5
    },
    {
        id: 12,
        nombre: "Frescor Ekos Pitanga Clasico",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Pitanga reúne notas frescas y afrutadas que brindan una sensación de ligereza y frescura en cualquier ocasión.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/Frescor Ekos Frutal.jpeg",
        imagen2: "img/Frescor Ekos Frutal2.jpeg",
        oferta: true,
        destacado: true,
        stock: 6
    },
    {
        id: 13,
        nombre: "Frescor Ekos Pitanga Preta",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Pitanga Preta combina delicadas notas florales con la frescura natural característica de la línea Ekos, aportando elegancia y suavidad.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/Frescor Ekos Floral.jpeg",
        imagen2: "img/Frescor Ekos Floral2.jpeg",
        oferta: true,
        destacado: true,
        stock: 7
    },
     {
        id: 14,
        nombre: "Frescor Ekos Castaña",
        codigo: "Nat0013",
        Descripción: "Frescor Ekos Castaña combina la riqueza de la castaña amazónica con delicadas notas amaderadas y cremosas. Una fragancia suave, cálida y envolvente que brinda una agradable sensación de confort y conexión con la naturaleza.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precio: 20000,
        imagen: "img/Frescor Ekos Castaña.jpeg",
        imagen2: "img/Frescor Ekos Castaña2.jpeg",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 15,
        codigo: "Nat0002",
        nombre: "Kaiak Urbe",
        descripcion: "Kaiak Urbe Masculino expresa un estilo moderno y urbano con una fragancia fresca, dinámica y de excelente duración.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak urbe.jpg",
        imagen2: "img/kaiak urbe2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
    },
    {
        id: 16,
        codigo: "Nat0002",
        nombre: "Kaiak Sonar",
        descripción: "Kaiak Sonar Masculino ofrece una fragancia fresca y moderna, con un aroma dinámico que transmite energía y personalidad para acompañarte durante todo el día.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak sonar.jpg",
        imagen2: "img/kaiak sonar 2.jpg",
        oferta: false,
        destacado: true,
        stock: 5
    },
    {
        id: 17,
        codigo: "Nat0002",
        nombre: "Kaiak Aero",
        descripción: "Kaiak Aero Masculino combina frescura y vitalidad en una fragancia inspirada en la sensación de libertad, ideal para hombres activos y aventureros.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak aero.jpg",
        imagen2: "img/kaiak aero2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
    },
    {
        id: 18,
        codigo: "Nat0002",
        nombre: "Kaiak Aventura",
        descripción: "Kaiak Aventura Masculino presenta una fragancia fresca y estimulante, creada para quienes disfrutan de nuevos desafíos, el movimiento y el contacto con la naturaleza.",,
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak aventura.jpg",
        imagen2: "img/kaiak aventura2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
    },
    {
        id: 19,
        codigo: "Nat0002",
        nombre: "Kaiak Eau Parfum",
        descripción: "Kaiak Eau de Parfum Masculino ofrece una versión más intensa de la línea Kaiak, con excelente duración y una presencia elegante sin perder su frescura característica.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak eau parfum.jpg",
        imagen2: "img/kaiak eau parfum2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
    },
    {
        id: 20,
        codigo: "Nat0002",
        nombre: "Kaiak Pulso",
        descripción: "Kaiak Pulso Masculino combina notas frescas y aromáticas para transmitir energía, confianza y un estilo moderno en cualquier ocasión.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak pulso.jpg",
        imagen2: "img/kaiak pulso2.jpg",
        oferta: false,
        destacado: true,
        stock: 5
    },
    {
        id: 21,
        codigo: "Nat0002",
        nombre: "Kaiak O2",
        descripción: "Kaiak O2 Masculino brinda una sensación de frescura y ligereza gracias a sus notas acuáticas y aromáticas, ideal para el uso diario.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak o2.jpg",
        imagen2: "img/kaiak o22.jpg",
        oferta: false,
        destacado: true,
        stock: 2
    },
    {
        id: 22,
        codigo: "Nat0002",
        nombre: "Kaiak Vital",
        descripción: "Kaiak Vital Masculino expresa vitalidad y bienestar con una fragancia fresca, versátil y de larga duración para acompañarte durante toda la jornada.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak vital.jpg",
        imagen2: "img/kaiak vital2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
    },
    {
        id: 23,
        codigo: "Nat0001",
        nombre: "Kaiak Clasico",
        descripción: "Kaiak Clásico Femenino combina delicadas notas florales y acuáticas en una fragancia femenina, ligera y versátil para disfrutar todos los días.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/kaiak clasicoF.jpg",
        imagen2: "img/kaiak clasicoF2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
    },
     {
        id: 24,
        codigo: "Nat0001",
        nombre: "Kaiak Oceano",
        descripción: "Kaiak Oceano Femenino está inspirado en la frescura del mar, ofreciendo una fragancia refrescante y llena de energía para mujeres activas.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/kaiak oceanoF.jpg",
        imagen2: "img/kaiak oceanoF2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
    },
     {
        id: 25,
        codigo: "Nat0001",
        nombre: "Kaiak Aventura",
        descripción: "Kaiak Aventura Femenino une frescura y personalidad en un perfume pensado para mujeres espontáneas que disfrutan de nuevas experiencias.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/kaiak aventuraF.jpg",
        imagen2: "img/kaiak aventuraF2.jpg",
        oferta: false,
        destacado: true,
        stock: 6
    },
      {
        id: 26,
        codigo: "Nat0001",
        nombre: "Kaiak Aero",
        descripción: "Kaiak Aero Femenino brinda una fragancia fresca y luminosa inspirada en la libertad y el movimiento. Su aroma moderno es ideal para acompañarte durante todo el día.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/kaiak aeroF.jpg",
        imagen2: "img/kaiak aeroF2.jpg",
        oferta: false,
        destacado: true,
        stock: 5
    },
      {
        id: 27,
        codigo: "Nat0001",
        nombre: "Kaiak Ultra",
        descripción: "Kaiak Ultra Femenino combina intensidad y frescura en una fragancia sofisticada, creada para mujeres que buscan dejar una impresión inolvidable.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/kaiak ultraF.jpg",
        imagen2: "img/kaiak ultraF2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
    },
    {
        id: 28,
        codigo: "Nat0001",
        nombre: "Kaiak O2",
        descripción: "Kaiak O2 Femenino ofrece una sensación de aire puro y frescura gracias a sus notas acuáticas y florales, perfecta para el uso cotidiano.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/kaiak o2F.jpg",
        imagen2: "img/kaiak o2F2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
    },
    {
        id: 29,
        codigo: "Nat0001",
        nombre: "Kaiak Vital",
        descripción: "Kaiak Vital Femenino transmite energía, bienestar y naturalidad con una fragancia fresca, delicada y de excelente duración.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/kaiak vitalF.jpg",
        imagen2: "img/kaiak vitalF2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
    },
     {
        id: 30,
        codigo: "Nat0003",
        nombre: "Essencial Oud",
        descripción: "Essencial Oud Masculino combina la intensidad del oud con notas amaderadas y especiadas, logrando una fragancia elegante, sofisticada y de gran personalidad.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/essencial oud.jpg",
        imagen2: "img/essencial oud2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
    },    
    {
        id: 31,
        codigo: "Nat0003",
        nombre: "Essencial Atrai",
        descripción: "Essencial Atrai Masculino es una fragancia envolvente y seductora con notas intensas que resaltan la elegancia y el carisma masculino.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/essencial atrai.jpg",
        imagen2: "img/essencial atrai2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
    },    
     {
        id: 32,
        codigo: "Nat0003",
        nombre: "Essencial Supreme",
        descripción: "Essencial Supreme Masculino ofrece una combinación de notas amaderadas y aromáticas que brindan una presencia refinada y duradera.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/essencial supreme.jpg",
        imagen2: "img/essencial supreme2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
     },
     {
        id: 33,
        codigo: "Nat0003",
        nombre: "Essencial Palo Santo",
        descripción: "Essencial Palo Santo Masculino une la fuerza del palo santo con acordes amaderados, creando una fragancia cálida, moderna y sofisticada.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/essencial palo santo.jpg",
        imagen2: "img/essencial palo santo2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
    },
    {
        id: 34,
        codigo: "Nat0003",
        nombre: "Essencial Exclusivo",
        descripción: "Essencial Exclusivo Masculino destaca por su aroma intenso y elegante, ideal para ocasiones especiales y para quienes buscan un perfume distintivo.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/essencial exclusivo.jpg",
        imagen2: "img/essencial exclusivo2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 35,
        codigo: "Nat0004",
        nombre: "Essencial Exclusivo",
        descripción: "Essencial Exclusivo Femenino combina notas florales y amaderadas en una fragancia sofisticada, elegante y de larga duración.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/essencial exclusivoF.jpg",
        imagen2: "img/essencial exclusivoF2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
        },
    {
        id: 36,
        codigo: "Nat0004",
        nombre: "Essencial Oud",
        descripcion: "Oud",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/essencial oudF.jpg",
        imagen2: "img/essencial oudF2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
     {
        id: 37,
        codigo: "Nat0004",
        nombre: "Essencial Clasico",
        descripcion: "Clasico",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/essencial clasicoF.jpg",
        imagen2: "img/essencial clasicoF2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
     {
        id: 38,
        codigo: "Nat0004",
        nombre: "Essencial Sentir",
        descripcion: "Sentir",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/essencial sentirF.jpg",
        imagen2: "img/essencial sentirF2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
        },
     {
        id: 39,
        codigo: "Nat0004",
        nombre: "Essencial Supreme",
        descripcion: "Supreme",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/essencial supremeF.jpg",
        imagen2: "img/essencial supremeF2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 40,
        codigo: "Nat0005",
        nombre: "Luna Clasico",
        descripcion: "Clasico",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"75ml",
        precio: 20000,
        imagen: "img/luna clasico 75ml.jpg",
        imagen2: "img/luna clasico 75ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 41,
        codigo: "Nat0005",
        nombre: "Luna Radiante",
        descripcion: "Radiante",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"75ml",
        precio: 20000,
        imagen: "img/luna radiante 75ml.jpg",
        imagen2: "img/luna radiante 75ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 42,
        codigo: "Nat0005",
        nombre: "Luna Absoluta",
        descripcion: "Absoluta",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"75ml",
        precio: 20000,
        imagen: "img/luna absoluta 75ml.jpg",
        imagen2: "img/luna absoluta 75ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 43,
        codigo: "Nat0005",
        nombre: "Luna Coraje",
        descripcion: "Coraje",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"75ml",
        precio: 20000,
        imagen: "img/luna coraje 75ml.jpg",
        imagen2: "img/luna coraje75ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 44,
        codigo: "Nat0006",
        nombre: "Luna Intenso",
        descripcion: "Intenso",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"50ml",
        precio: 20000,
        imagen: "img/luna intenso 50ml.jpg",
        imagen2: "img/luna intenso 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 45,
        codigo: "Nat0006",
        nombre: "Luna Actitude",
        descripcion: "Actitude",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"50ml",
        precio: 20000,
        imagen: "img/luna actitude 50ml.jpg",
        imagen2: "img/luna actitude 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 46,
        codigo: "Nat0006",
        nombre: "Luna Legado",
        descripcion: "Legado",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"50ml",
        precio: 20000,
        imagen: "img/luna legado 50ml.jpg",
        imagen2: "img/luna legado 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 47,
        codigo: "Nat0006",
        nombre: "Luna Radiante",
        descripcion: "Radiante",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"50ml",
        precio: 20000,
        imagen: "img/luna radiante 50ml.jpg",
        imagen2: "img/luna radiante 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 48,
        codigo: "Nat0007",
        nombre: "Ilia Secreto",
        descripcion: "Secreto",
        categoria: "Perfumes",
        subcategoria:"Ilia",
        precio: 20000,
        imagen: "img/ilia secreto 50ml.jpg",
        imagen2: "img/ilia secreto 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
        },
    {
        id: 49,
        codigo: "Nat0007",
        nombre: "Ilia Clasico",
        descripcion: "Clasico",
        categoria: "Perfumes",
        subcategoria:"Ilia",
        precio: 20000,
        imagen: "img/ilia clasico 50ml.jpg",
        imagen2: "img/ilia clasico 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
    {
        id: 50,
        codigo: "Nat0008",
        nombre: "Homen Elo",
        descripcion: "Elo",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen elo.jpg",
        imagen2: "img/homen elo2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 51,
        codigo: "Nat0008",
        nombre: "Homen Neo",
        descripcion: "Neo",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen neo.jpg",
        imagen2: "img/homen neo2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
        },
    {
        id: 52,
        codigo: "Nat0008",
        nombre: "Homen Coragio",
        descripcion: "Coragio",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen coragio.jpg",
        imagen2: "img/homen coragio2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 53,
        codigo: "Nat0008",
        nombre: "Homen Clasico",
        descripcion: "Clasico",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen clasico.jpg",
        imagen2: "img/homen clasico2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 54,
        codigo: "Nat0008",
        nombre: "Homen Identidad",
        descripcion: "Identidad",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen identidad.jpg",
        imagen2: "img/homen identidad2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 55,
        codigo: "Nat0008",
        nombre: "Homen Potence",
        descripcion: "Potence",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen potence.jpg",
        imagen2: "img/homen potence2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 56,
        codigo: "Nat0008",
        nombre: "Homen Essence",
        descripcion: "Essence",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen essence.jpg",
        imagen2: "img/homen essence2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 57,
        codigo: "Nat0008",
        nombre: "Homen Nos",
        descripcion: "Nos",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen nos.jpg",
        imagen2: "img/homen nos2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 58,
        codigo: "Nat0009",
        nombre: "Humor Proprio",
        descripcion: "Proprio",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor proprioF.jpg",
        imagen2: "img/humor proprioF2.jpg",
        oferta: false,
        destacado: true,
        stock: 9
        },
     {
        id: 59,
        codigo: "Nat0009",
        nombre: "Humor Meu Primeiro",
        descripcion: "Meu Primeiro",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor meu primeiroF.jpg",
        imagen2: "img/humor meu primeiroF2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
    {
        id: 60,
        codigo: "Nat0009",
        nombre: "Humor Beijo",
        descripcion: "Beijo",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor beijoF.jpg",
        imagen2: "img/humor beijoF2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
    {
        id: 61,
        codigo: "Nat0009",
        nombre: "Humor Galaxia",
        descripcion: "Galaxia",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor galaxiaF.jpg",
        imagen2: "img/humor galaxiaF2.jpg",
        oferta: false,
        destacado: true,
        stock: 5
        },
    {
        id: 62,
        codigo: "Nat0009",
        nombre: "Humor On Line",
        descripcion: "On Line",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor on lineF.jpg",
        imagen2: "img/humor on lineF2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
     {
        id: 63,
        codigo: "Nat0009",
        nombre: "Humor Festival",
        descripcion: "Festival",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor festivalF.jpg",
        imagen2: "img/humor festivalF2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
        },
     {
        id: 64,
        codigo: "Nat0009",
        nombre: "Humor Quimica",
        descripcion: "Quimica",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor quimicaF.jpg",
        imagen2: "img/humor quimicaF2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
        },
     {
        id: 65,
        codigo: "Nat0009",
        nombre: "Humor Minha Vida",
        descripcion: "Minha Vida",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor minha vidaF.jpg",
        imagen2: "img/humor minha vidaF2.jpg",
        oferta: false,
        destacado: true,
        stock: 5
        },
     {
        id: 66,
        codigo: "Nat0010",
        nombre: "Humor Adois",
        descripcion: "Adois",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/humor adoisM.jpg",
        imagen2: "img/humor adoisM2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 67,
        codigo: "Nat0010",
        nombre: "Humor E Paz",
        descripcion: "E Paz",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/humor e pazM.jpg",
        imagen2: "img/humor e pazM2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 68,
        codigo: "Nat0010",
        nombre: "Humor Beijo",
        descripcion: "Beijo",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/humor beijoM.jpg",
        imagen2: "img/humor beijoM2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
        },
    {
        id: 69,
        codigo: "Nat0010",
        nombre: "Humor On Line",
        descripcion: "On Line",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/humor on lineM.jpg",
        imagen2: "img/humor on lineM2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
        },
    {
        id: 70,
        codigo: "Nat0010",
        nombre: "Humor Conexion",
        descripcion: "Conexion",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/humor conexionM.jpg",
        imagen2: "img/humor conexionM2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
        },
    {
        id: 71,
        codigo: "Nat0011",
        nombre: "Humor Liberta",
        descripcion: "Liberta",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Unisex",
        precio: 20000,
        imagen: "img/humor libertaU.jpg",
        imagen2: "img/humor libertaU2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
    {
        id: 72,
        codigo: "Nat0011",
        nombre: "Humor Transforma",
        descripcion: "Transforma",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Unisex",
        precio: 20000,
        imagen: "img/humor transformaU.jpg",
        imagen2: "img/humor transformaU2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
    {
        id: 73,
        codigo: "Nat0011",
        nombre: "Humor Envolve",
        descripcion: "Envolve",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Unisex",
        precio: 20000,
        imagen: "img/humor envolveU.jpg",
        imagen2: "img/humor envolveU2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
        },
    {
        id: 74,
        codigo: "Nat0012",
        nombre: "Humor Minha Vida",
        descripcion: "Minha Vida",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Mini 25ml",
        precio: 20000,
        imagen: "img/humor meu primeiroMini.jpg",
        oferta: false,
        destacado: true,
        stock: 8
        },
    {
        id: 75,
        codigo: "Nat0012",
        nombre: "Humor Dose",
        descripcion: "Dose",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Mini 25ml",
        precio: 20000,
        imagen: "img/humor doseMini.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        }
];
