const productos = [
    {
        id: 1,
        codigo: "Nat0010",
        nombre: "Kit Tododia Algodón",
        descripcion: "Crema hidratante 400 ml + Body Splash 200 ml",
        categoria: "Tododia",
        subcategoria:"Cremas",
        precio: 31900,
        imagen: "img/algodon.jpeg",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 2,
        codigo: "Nat0010",
        nombre: "Kit Tododia Acerola",
        descripcion: "Crema hidratante + Body Splash",
        categoria: "Tododia",
        subcategoria:"Cremas",
        precio: 31900,
        imagen: "img/acerola.jpeg",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 3,
        nombre: "Pitanga Preta",
        descripcion: "Perfume Ekos 150 ml",
        categoria: "Perfumes",
        subcategoria:"Ekos",
        precio: 30000,
        imagen: "img/pitanga.jpeg",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 4,
        nombre: "Kit Humor Rojo",
        descripcion: "Labial + Esmalte + Perfume",
        categoria: "Maquillaje",
        subcategoria:"Humor",
        precio: 20000,
        imagen: "img/humor.png",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 5,
        nombre: "Frescor Ekos Ishpink",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Ishpink destaca por su aroma fresco y sofisticado con delicadas notas florales y amaderadas. Una fragancia elegante que expresa la riqueza y autenticidad de la naturaleza brasileña.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precio: 20000,
        imagen: "img/Frescor-Ekos-Ishpink.jpg",
        imagen2: "img/Frescor-Ekos-Ishpink2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
    },
     {
        id: 6,
        nombre: "Frescor Ekos Tucuma",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Tucumã combina notas frescas y cremosas inspiradas en la biodiversidad amazónica. Una fragancia moderna, envolvente y llena de vitalidad para acompañarte todos los días.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precio: 20000,
        imagen: "img/Frescor-Ekos-Tucuma.jpg",
        imagen2: "img/Frescor-Ekos-Tucuma2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
    },
    {
        id: 7,
        codigo: "Nat0002",
        nombre: "Kaiak Clasico",
        descripcion: "Kaiak Clásico Masculino combina notas cítricas, aromáticas y acuáticas para ofrecer una fragancia fresca, versátil y perfecta para el uso diario.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/kaiak.jpg",
        imagen2: "img/kaiak2.jpg",
        oferta: true,
        destacado: true,
        stock: 4
    },
     {
        id: 8,
        codigo: "Nat0002",
        nombre: "Kaiak Oceano",
        descripcion: "Kaiak Oceano Masculino está inspirado en la fuerza y frescura del mar. Un perfume revitalizante ideal para hombres activos.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/kaiak oceano.jpeg",
        imagen2: "img/kaiak oceano2.jpeg",
        oferta: true,
        destacado: true,
        stock: 4
    },
    {
        id: 9,
        nombre: "Frescor Ekos Acai",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Açaí ofrece una fragancia ligera y refrescante con notas frutales inspiradas en la riqueza de la biodiversidad brasileña.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precio: 20000,
        imagen: "img/Frescor Ekos Acai2.jpeg",
        imagen2: "img/Frescor Ekos Acai.jpeg",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 10,
        nombre: "Frescor Ekos Maracuya",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Maracuyá combina un aroma tropical y fresco que transmite energía, alegría y bienestar durante todo el día.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precio: 20000,
        imagen: "img/Frescor Ekos Mara2.jpeg",
        imagen2: "img/Frescor Ekos Mara.jpeg",
        oferta: false,
        destacado: true,
        stock: 4
    },
    {
        id: 11,
        nombre: "Frescor Ekos Cacau",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Cacau presenta una fragancia cálida y envolvente inspirada en el cacao brasileño, ideal para quienes buscan un aroma con personalidad.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/Frescor Ekos Cacau.jpeg",
        imagen2: "img/Frescor Ekos Cacau2.jpeg",
        oferta: true,
        destacado: true,
        stock: 5
    },
    {
        id: 12,
        nombre: "Frescor Ekos Pitanga Clasico",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Pitanga reúne notas frescas y afrutadas que brindan una sensación de ligereza y frescura en cualquier ocasión.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/Frescor Ekos Frutal.jpeg",
        imagen2: "img/Frescor Ekos Frutal2.jpeg",
        oferta: true,
        destacado: true,
        stock: 6
    },
    {
        id: 13,
        nombre: "Frescor Ekos Pitanga Preta",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Pitanga Preta combina delicadas notas florales con la frescura natural característica de la línea Ekos, aportando elegancia y suavidad.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/Frescor Ekos Floral.jpeg",
        imagen2: "img/Frescor Ekos Floral2.jpeg",
        oferta: true,
        destacado: true,
        stock: 7
    },
     {
        id: 14,
        nombre: "Frescor Ekos Castaña",
        codigo: "Nat0013",
        descripcion: "Frescor Ekos Castaña combina la riqueza de la castaña amazónica con delicadas notas amaderadas y cremosas. Una fragancia suave, cálida y envolvente que brinda una agradable sensación de confort y conexión con la naturaleza.",
        categoria: "Perfumes",
        subcategoria:"Frescor Ekos",
        precio: 20000,
        imagen: "img/Frescor Ekos Castaña.jpeg",
        imagen2: "img/Frescor Ekos Castaña2.jpeg",
        oferta: false,
        destacado: true,
        stock: 8
    },
    {
        id: 15,
        codigo: "Nat0002",
        nombre: "Kaiak Urbe",
        descripcion: "Kaiak Urbe Masculino expresa un estilo moderno y urbano con una fragancia fresca, dinámica y de excelente duración.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak urbe.jpg",
        imagen2: "img/kaiak urbe2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
    },
    {
        id: 16,
        codigo: "Nat0002",
        nombre: "Kaiak Sonar",
        descripcion: "Kaiak Sonar Masculino ofrece una fragancia fresca y moderna, con un aroma dinámico que transmite energía y personalidad para acompañarte durante todo el día.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak sonar.jpg",
        imagen2: "img/kaiak sonar 2.jpg",
        oferta: false,
        destacado: true,
        stock: 5
    },
    {
        id: 17,
        codigo: "Nat0002",
        nombre: "Kaiak Aero",
        descripcion: "Kaiak Aero Masculino combina frescura y vitalidad en una fragancia inspirada en la sensación de libertad, ideal para hombres activos y aventureros.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak aero.jpg",
        imagen2: "img/kaiak aero2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
    },
    {
        id: 18,
        codigo: "Nat0002",
        nombre: "Kaiak Aventura",
        descripcion: "Kaiak Aventura Masculino presenta una fragancia fresca y estimulante, creada para quienes disfrutan de nuevos desafíos, el movimiento y el contacto con la naturaleza.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak aventura.jpg",
        imagen2: "img/kaiak aventura2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
    },
    {
        id: 19,
        codigo: "Nat0002",
        nombre: "Kaiak Eau Parfum",
        descripcion: "Kaiak Eau de Parfum Masculino ofrece una versión más intensa de la línea Kaiak, con excelente duración y una presencia elegante sin perder su frescura característica.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak eau parfum.jpg",
        imagen2: "img/kaiak eau parfum2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
    },
    {
        id: 20,
        codigo: "Nat0002",
        nombre: "Kaiak Pulso",
        descripcion: "Kaiak Pulso Masculino combina notas frescas y aromáticas para transmitir energía, confianza y un estilo moderno en cualquier ocasión.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak pulso.jpg",
        imagen2: "img/kaiak pulso2.jpg",
        oferta: false,
        destacado: true,
        stock: 5
    },
    {
        id: 21,
        codigo: "Nat0002",
        nombre: "Kaiak O2",
        descripcion: "Kaiak O2 Masculino brinda una sensación de frescura y ligereza gracias a sus notas acuáticas y aromáticas, ideal para el uso diario.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak o2.jpg",
        imagen2: "img/kaiak o22.jpg",
        oferta: false,
        destacado: true,
        stock: 2
    },
    {
        id: 22,
        codigo: "Nat0002",
        nombre: "Kaiak Vital",
        descripcion: "Kaiak Vital Masculino expresa vitalidad y bienestar con una fragancia fresca, versátil y de larga duración para acompañarte durante toda la jornada.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/kaiak vital.jpg",
        imagen2: "img/kaiak vital2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
    },
    {
        id: 23,
        codigo: "Nat0001",
        nombre: "Kaiak Clasico",
        descripcion: "Kaiak Clásico Femenino combina delicadas notas florales y acuáticas en una fragancia femenina, ligera y versátil para disfrutar todos los días.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/kaiak clasicoF.jpg",
        imagen2: "img/kaiak clasicoF2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
    },
     {
        id: 24,
        codigo: "Nat0001",
        nombre: "Kaiak Oceano",
        descripcion: "Kaiak Oceano Femenino está inspirado en la frescura del mar, ofreciendo una fragancia refrescante y llena de energía para mujeres activas.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precioAnterior: 30000,
        precio: 20000,
        imagen: "img/kaiak oceanoF.jpg",
        imagen2: "img/kaiak oceanoF2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
    },
     {
        id: 25,
        codigo: "Nat0001",
        nombre: "Kaiak Aventura",
        descripcion: "Kaiak Aventura Femenino une frescura y personalidad en un perfume pensado para mujeres espontáneas que disfrutan de nuevas experiencias.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/kaiak aventuraF.jpg",
        imagen2: "img/kaiak aventuraF2.jpg",
        oferta: false,
        destacado: true,
        stock: 6
    },
      {
        id: 26,
        codigo: "Nat0001",
        nombre: "Kaiak Aero",
        descripcion: "Kaiak Aero Femenino brinda una fragancia fresca y luminosa inspirada en la libertad y el movimiento. Su aroma moderno es ideal para acompañarte durante todo el día.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/kaiak aeroF.jpg",
        imagen2: "img/kaiak aeroF2.jpg",
        oferta: false,
        destacado: true,
        stock: 5
    },
      {
        id: 27,
        codigo: "Nat0001",
        nombre: "Kaiak Ultra",
        descripcion: "Kaiak Ultra Femenino combina intensidad y frescura en una fragancia sofisticada, creada para mujeres que buscan dejar una impresión inolvidable.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/kaiak ultraF.jpg",
        imagen2: "img/kaiak ultraF2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
    },
    {
        id: 28,
        codigo: "Nat0001",
        nombre: "Kaiak O2",
        descripcion: "Kaiak O2 Femenino ofrece una sensación de aire puro y frescura gracias a sus notas acuáticas y florales, perfecta para el uso cotidiano.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/kaiak o2F.jpg",
        imagen2: "img/kaiak o2F2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
    },
    {
        id: 29,
        codigo: "Nat0001",
        nombre: "Kaiak Vital",
        descripcion: "Kaiak Vital Femenino transmite energía, bienestar y naturalidad con una fragancia fresca, delicada y de excelente duración.",
        categoria: "Perfumes",
        subcategoria:"Kaiak",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/kaiak vitalF.jpg",
        imagen2: "img/kaiak vitalF2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
    },
     {
        id: 30,
        codigo: "Nat0003",
        nombre: "Essencial Oud",
        descripcion: "Essencial Oud Masculino combina la intensidad del oud con notas amaderadas y especiadas, logrando una fragancia elegante, sofisticada y de gran personalidad.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/essencial oud.jpg",
        imagen2: "img/essencial oud2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
    },    
    {
        id: 31,
        codigo: "Nat0003",
        nombre: "Essencial Atrai",
        descripcion: "Essencial Atrai Masculino es una fragancia envolvente y seductora con notas intensas que resaltan la elegancia y el carisma masculino.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/essencial atrai.jpg",
        imagen2: "img/essencial atrai2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
    },    
     {
        id: 32,
        codigo: "Nat0003",
        nombre: "Essencial Supreme",
        descripcion: "Essencial Supreme Masculino ofrece una combinación de notas amaderadas y aromáticas que brindan una presencia refinada y duradera.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/essencial supreme.jpg",
        imagen2: "img/essencial supreme2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
     },
     {
        id: 33,
        codigo: "Nat0003",
        nombre: "Essencial Palo Santo",
        descripcion: "Essencial Palo Santo Masculino une la fuerza del palo santo con acordes amaderados, creando una fragancia cálida, moderna y sofisticada.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/essencial palo santo.jpg",
        imagen2: "img/essencial palo santo2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
    },
    {
        id: 34,
        codigo: "Nat0003",
        nombre: "Essencial Exclusivo",
        descripcion: "Essencial Exclusivo Masculino destaca por su aroma intenso y elegante, ideal para ocasiones especiales y para quienes buscan un perfume distintivo.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/essencial exclusivo.jpg",
        imagen2: "img/essencial exclusivo2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 35,
        codigo: "Nat0004",
        nombre: "Essencial Exclusivo",
        descripcion: "Essencial Exclusivo Femenino combina notas florales y amaderadas en una fragancia sofisticada, elegante y de larga duración.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/essencial exclusivoF.jpg",
        imagen2: "img/essencial exclusivoF2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
        },
    {
        id: 36,
        codigo: "Nat0004",
        nombre: "Essencial Oud",
        descripcion: "Essencial Oud Femenino combina la intensidad del oud con delicadas notas florales y amaderadas. Una fragancia sofisticada, envolvente y de excelente duración.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/essencial oudF.jpg",
        imagen2: "img/essencial oudF2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
     {
        id: 37,
        codigo: "Nat0004",
        nombre: "Essencial Clasico",
        descripcion: "Essencial Clásico Femenino ofrece una combinación elegante de notas florales y amaderadas, ideal para mujeres que buscan una fragancia refinada para todos los días.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/essencial clasicoF.jpg",
        imagen2: "img/essencial clasicoF2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
     {
        id: 38,
        codigo: "Nat0004",
        nombre: "Essencial Sentir",
        descripcion: "Essencial Sentir Femenino expresa sensibilidad y elegancia con un aroma floral moderno, delicado y de larga duración para cualquier ocasión.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/essencial sentirF.jpg",
        imagen2: "img/essencial sentirF2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
        },
     {
        id: 39,
        codigo: "Nat0004",
        nombre: "Essencial Supreme",
        descripcion: "Essencial Supreme Femenino reúne notas intensas y sofisticadas que resaltan la personalidad y la elegancia con una excelente fijación.",
        categoria: "Perfumes",
        subcategoria:"Essencial",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/essencial supremeF.jpg",
        imagen2: "img/essencial supremeF2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 40,
        codigo: "Nat0005",
        nombre: "Luna Clasico",
        descripcion: "Luna Clásico combina delicadas notas florales y frutales con un fondo amaderado, creando una fragancia femenina, elegante y atemporal.",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"75ml",
        precio: 20000,
        imagen: "img/luna clasico 75ml.jpg",
        imagen2: "img/luna clasico 75ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 41,
        codigo: "Nat0005",
        nombre: "Luna Radiante",
        descripcion: "Luna Radiante transmite luminosidad y frescura con un delicado equilibrio entre notas florales y frutales, ideal para el uso diario.",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"75ml",
        precio: 20000,
        imagen: "img/luna radiante 75ml.jpg",
        imagen2: "img/luna radiante 75ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 42,
        codigo: "Nat0005",
        nombre: "Luna Absoluta",
        descripcion: "Luna Absoluta ofrece una fragancia intensa y sofisticada con notas florales y amaderadas que resaltan la elegancia femenina.",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"75ml",
        precio: 20000,
        imagen: "img/luna absoluta 75ml.jpg",
        imagen2: "img/luna absoluta 75ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 43,
        codigo: "Nat0005",
        nombre: "Luna Coraje",
        descripcion: "Luna Coraje inspira fuerza y confianza con una combinación moderna de notas florales, especiadas y amaderadas.",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"75ml",
        precio: 20000,
        imagen: "img/luna coraje 75ml.jpg",
        imagen2: "img/luna coraje75ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 44,
        codigo: "Nat0006",
        nombre: "Luna Intenso",
        descripcion: "Luna Intenso presenta una fragancia envolvente y elegante con notas profundas y sofisticadas, ideal para quienes buscan una mayor intensidad.",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"50ml",
        precio: 20000,
        imagen: "img/luna intenso 50ml.jpg",
        imagen2: "img/luna intenso 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 45,
        codigo: "Nat0006",
        nombre: "Luna Actitude",
        descripcion: "Luna Attitude combina modernidad, personalidad y elegancia en una fragancia floral amaderada de excelente duración.",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"50ml",
        precio: 20000,
        imagen: "img/luna actitude 50ml.jpg",
        imagen2: "img/luna actitude 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 46,
        codigo: "Nat0006",
        nombre: "Luna Legado",
        descripcion: "Luna Legado 50 ml expresa sofisticación y feminidad con una armoniosa combinación de notas florales, amaderadas y ligeramente dulces.",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"50ml",
        precio: 20000,
        imagen: "img/luna legado 50ml.jpg",
        imagen2: "img/luna legado 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 47,
        codigo: "Nat0006",
        nombre: "Luna Radiante",
        descripcion: "Luna Radiante 50 ml transmite frescura, luminosidad y feminidad con una delicada combinación de notas florales y frutales. Ideal para acompañarte todos los días.",
        categoria: "Perfumes",
        subcategoria:"Luna",
        subcategoria3:"50ml",
        precio: 20000,
        imagen: "img/luna radiante 50ml.jpg",
        imagen2: "img/luna radiante 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 48,
        codigo: "Nat0007",
        nombre: "Ilia Secreto",
        descripcion: "Ilía Secreto revela una fragancia intensa y sofisticada con acordes florales y amaderados que destacan la elegancia y el misterio femenino.",
        categoria: "Perfumes",
        subcategoria:"Ilia",
        precio: 20000,
        imagen: "img/ilia secreto 50ml.jpg",
        imagen2: "img/ilia secreto 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
        },
    {
        id: 49,
        codigo: "Nat0007",
        nombre: "Ilia Clasico",
        descripcion: "Ilía Clásico combina delicadas notas florales con un fondo cálido y elegante, creando una fragancia femenina, versátil y de excelente duración.",
        categoria: "Perfumes",
        subcategoria:"Ilia",
        precio: 20000,
        imagen: "img/ilia clasico 50ml.jpg",
        imagen2: "img/ilia clasico 50ml2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
    {
        id: 50,
        codigo: "Nat0008",
        nombre: "Homen Elo",
        descripcion: "Homen Elo expresa confianza y modernidad con una fragancia fresca y amaderada que acompaña al hombre en cada desafío del día.",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen elo.jpg",
        imagen2: "img/homen elo2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 51,
        codigo: "Nat0008",
        nombre: "Homen Neo",
        descripcion: "Homen Neo combina frescura, energía y sofisticación en una fragancia moderna con notas aromáticas y amaderadas de larga duración.",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen neo.jpg",
        imagen2: "img/homen neo2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
        },
    {
        id: 52,
        codigo: "Nat0008",
        nombre: "Homen Coragio",
        descripcion: "Homen Coragio refleja fuerza, valentía y personalidad mediante una fragancia intensa con notas especiadas y amaderadas que dejan una impresión inolvidable.",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen coragio.jpg",
        imagen2: "img/homen coragio2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 53,
        codigo: "Nat0008",
        nombre: "Homen Clasico",
        descripcion: "Homen Clásico ofrece una combinación equilibrada de notas frescas, amaderadas y aromáticas, ideal para quienes buscan elegancia en cualquier ocasión.",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen clasico.jpg",
        imagen2: "img/homen clasico2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 54,
        codigo: "Nat0008",
        nombre: "Homen Identidad",
        descripcion: "Homen Identidad destaca por su aroma moderno y auténtico, con acordes amaderados y especiados que reflejan seguridad y personalidad.",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen identidad.jpg",
        imagen2: "img/homen identidad2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 55,
        codigo: "Nat0008",
        nombre: "Homen Potence",
        descripcion: "Homen Potence combina intensidad y sofisticación con notas amaderadas y orientales que brindan una fragancia masculina de gran presencia.",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen potence.jpg",
        imagen2: "img/homen potence2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 56,
        codigo: "Nat0008",
        nombre: "Homen Essence",
        descripcion: "Homen Essence ofrece una fragancia refinada con un equilibrio entre notas frescas y amaderadas, ideal para quienes valoran la elegancia cotidiana.",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen essence.jpg",
        imagen2: "img/homen essence2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 57,
        codigo: "Nat0008",
        nombre: "Homen Nos",
        descripcion: "Homen Nós celebra la conexión y la autenticidad con una fragancia moderna que combina frescura, calidez y excelente fijación.",
        categoria: "Perfumes",
        subcategoria:"Homen",
        precio: 20000,
        imagen: "img/homen nos.jpg",
        imagen2: "img/homen nos2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
    {
        id: 58,
        codigo: "Nat0009",
        nombre: "Humor Proprio",
        descripcion: "Humor Próprio Femenino celebra la autenticidad y la libertad de ser vos misma con una fragancia alegre, moderna y de excelente duración.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor proprioF.jpg",
        imagen2: "img/humor proprioF2.jpg",
        oferta: false,
        destacado: true,
        stock: 9
        },
     {
        id: 59,
        codigo: "Nat0009",
        nombre: "Humor Meu Primeiro",
        descripcion: "Humor Meu Primeiro Amor combina delicadas notas florales y frutales en una fragancia romántica, fresca y llena de dulzura para todos los días.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor meu primeiroF.jpg",
        imagen2: "img/humor meu primeiroF2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
    {
        id: 60,
        codigo: "Nat0009",
        nombre: "Humor Beijo",
        descripcion: "Humor Beijo Femenino transmite alegría y espontaneidad con un aroma vibrante de notas frutales y florales que invitan a disfrutar cada momento.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor beijoF.jpg",
        imagen2: "img/humor beijoF2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
    {
        id: 61,
        codigo: "Nat0009",
        descripcion: "Humor Galáxia Femenino presenta una fragancia moderna y sorprendente con acordes florales, frutales y amaderados que reflejan creatividad y personalidad.",
        descripcion: "Galaxia",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor galaxiaF.jpg",
        imagen2: "img/humor galaxiaF2.jpg",
        oferta: false,
        destacado: true,
        stock: 5
        },
    {
        id: 62,
        codigo: "Nat0009",
        nombre: "Humor On Line",
        descripcion: "Humor On Line Femenino expresa frescura y energía con una combinación de notas cítricas, florales y amaderadas, ideal para mujeres dinámicas.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor on lineF.jpg",
        imagen2: "img/humor on lineF2.jpg",
        oferta: false,
        destacado: true,
        stock: 1
        },
     {
        id: 63,
        codigo: "Nat0009",
        nombre: "Humor Festival",
        descripcion: "Humor Festival Femenino transmite diversión, color y libertad con una fragancia vibrante de notas frutales y florales para vivir cada día como una celebración.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor festivalF.jpg",
        imagen2: "img/humor festivalF2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
        },
     {
        id: 64,
        codigo: "Nat0009",
        nombre: "Humor Quimica",
        descripcion: "Humor Química Femenino combina delicadas notas florales y especiadas en una fragancia envolvente que resalta la conexión, la pasión y la feminidad.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor quimicaF.jpg",
        imagen2: "img/humor quimicaF2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
        },
     {
        id: 65,
        codigo: "Nat0009",
        nombre: "Humor Minha Vida",
        descripcion: "Humor Minha Vida Femenino ofrece una fragancia cálida, alegre y delicadamente floral que acompaña los momentos más especiales con un toque de ternura.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Femenino",
        precio: 20000,
        imagen: "img/humor minha vidaF.jpg",
        imagen2: "img/humor minha vidaF2.jpg",
        oferta: false,
        destacado: true,
        stock: 5
        },
     {
        id: 66,
        codigo: "Nat0010",
        nombre: "Humor Adois",
        descripcion: "Humor A Dois Masculino combina frescura y sensualidad en una fragancia moderna con notas aromáticas y amaderadas, perfecta para compartir grandes momentos.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/humor adoisM.jpg",
        imagen2: "img/humor adoisM2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 67,
        codigo: "Nat0010",
        nombre: "Humor E Paz",
        descripcion: "Humor e Paz Masculino transmite tranquilidad y optimismo mediante una fragancia fresca, relajante y versátil, ideal para el uso diario.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/humor e pazM.jpg",
        imagen2: "img/humor e pazM2.jpg",
        oferta: false,
        destacado: true,
        stock: 0
        },
    {
        id: 68,
        codigo: "Nat0010",
        nombre: "Humor Beijo",
        descripcion: "Humor Beijo Masculino ofrece un aroma vibrante y seductor con notas frescas y amaderadas que destacan una personalidad espontánea y segura.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/humor beijoM.jpg",
        imagen2: "img/humor beijoM2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
        },
    {
        id: 69,
        codigo: "Nat0010",
        nombre: "Humor On Line",
        descripcion: "Humor On Line Masculino reúne acordes cítricos, aromáticos y amaderados en una fragancia moderna que acompaña el ritmo de todos los días.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/humor on lineM.jpg",
        imagen2: "img/humor on lineM2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
        },
    {
        id: 70,
        codigo: "Nat0010",
        nombre: "Humor Conexion",
        descripcion: "Humor Conexión Masculino refleja cercanía, energía y autenticidad con una fragancia fresca de excelente duración y personalidad inconfundible.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Masculino",
        precio: 20000,
        imagen: "img/humor conexionM.jpg",
        imagen2: "img/humor conexionM2.jpg",
        oferta: false,
        destacado: true,
        stock: 2
        },
    {
        id: 71,
        codigo: "Nat0011",
        nombre: "Humor Liberta",
        descripcion: "Humor Liberta Unisex celebra la libertad de expresar quién sos con una fragancia equilibrada, fresca y moderna pensada para todos.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Unisex",
        precio: 20000,
        imagen: "img/humor libertaU.jpg",
        imagen2: "img/humor libertaU2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
    {
        id: 72,
        codigo: "Nat0011",
        nombre: "Humor Transforma",
        descripcion: "Humor Transforma Unisex inspira nuevos comienzos con una combinación de notas frescas, florales y amaderadas que evolucionan a lo largo del día.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Unisex",
        precio: 20000,
        imagen: "img/humor transformaU.jpg",
        imagen2: "img/humor transformaU2.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
    {
        id: 73,
        codigo: "Nat0011",
        nombre: "Humor Envolve",
        descripcion: "Humor Envolve Unisex envuelve los sentidos con una fragancia armoniosa que combina frescura, calidez y un toque sofisticado para cualquier ocasión.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Unisex",
        precio: 20000,
        imagen: "img/humor envolveU.jpg",
        imagen2: "img/humor envolveU2.jpg",
        oferta: false,
        destacado: true,
        stock: 3
        },
    {
        id: 74,
        codigo: "Nat0012",
        nombre: "Humor Minha Vida",
        descripcion: "Humor Minha Vida Mini 25 ml conserva toda la alegría y dulzura de la fragancia original en un práctico formato ideal para llevar siempre con vos.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Mini 25ml",
        precio: 20000,
        imagen: "img/humor meu primeiroMini.jpg",
        oferta: false,
        destacado: true,
        stock: 8
        },
    {
        id: 75,
        codigo: "Nat0012",
        nombre: "Humor Dose",
        descripcion: "Humor Dose Mini 25 ml ofrece una versión compacta de esta fragancia moderna, fresca y divertida, perfecta para disfrutar en cualquier momento y lugar.",
        categoria: "Perfumes",
        subcategoria:"Humor",
        subcategoria3:"Mini 25ml",
        precio: 20000,
        imagen: "img/humor doseMini.jpg",
        oferta: false,
        destacado: true,
        stock: 4
        },
    {
    id: 76,
    codigo: "Nat0014",
    nombre: "Tododia Cereza y Avellana",
    descripcion: "Crema hidratante corporal Tododia Cereza y Avellana con nutrición profunda, textura liviana y rápida absorción. Deja la piel suave, perfumada e hidratada durante todo el día.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "400 ml",
    precio: 20000,
    imagen: "img/tododia-cereza-avellana.jpg",
    imagen2: "img/tododia-cereza-avellana2.jpg",
    oferta: false,
    destacado: true,
    stock: 3
},
{
    id: 77,
    codigo: "Nat0014",
    nombre: "Tododia Cereza Negra y Praliné",
    descripcion: "Crema hidratante corporal con una fragancia intensa y envolvente de cereza negra y praliné. Nutre profundamente la piel y brinda hidratación prolongada.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "400 ml",
    precio: 20000,
    imagen: "img/tododia-cereza-negra-praline.jpg",
    imagen2: "img/tododia-cereza-negra-praline2.jpg",
    oferta: false,
    destacado: true,
    stock: 24
},
{
    id: 78,
    codigo: "Nat0014",
    nombre: "Tododia Pera y Flor de Loto",
    descripcion: "Crema hidratante corporal con una delicada combinación de pera y flor de loto. Su fórmula deja la piel nutrida, sedosa y con un perfume fresco.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "400 ml",
    precio: 20000,
    imagen: "img/tododia-pera-flor-loto.jpg",
    imagen2: "img/tododia-pera-flor-loto2.jpg",
    oferta: false,
    destacado: true,
    stock: 4
},
{
    id: 79,
    codigo: "Nat0014",
    nombre: "Tododia Frutas Rojas",
    descripcion: "Crema hidratante corporal con un aroma frutal intenso y femenino. Nutre profundamente la piel y proporciona una agradable sensación de suavidad.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "400 ml",
    precio: 20000,
    imagen: "img/tododia-frutas-rojas.jpg",
    imagen2: "img/tododia-frutas-rojas2.jpg",
    oferta: false,
    destacado: true,
    stock: 0
},
{
    id: 80,
    codigo: "Nat0014",
    nombre: "Tododia Frambuesa y Pimienta Rosa",
    descripcion: "Crema hidratante corporal con una fragancia sofisticada que combina la dulzura de la frambuesa con el toque especiado de la pimienta rosa.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "400 ml",
    precio: 20000,
    imagen: "img/tododia-frambuesa-pimienta-rosa.jpg",
    imagen2: "img/tododia-frambuesa-pimienta-rosa2.jpg",
    oferta: false,
    destacado: true,
    stock: 2
},
{
    id: 81,
    codigo: "Nat0014",
    nombre: "Tododia Frambuesa y Pimienta Roja",
    descripcion: "Crema hidratante corporal con un aroma vibrante y moderno. Su textura cremosa hidrata profundamente y deja la piel delicadamente perfumada.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "400 ml",
    precio: 20000,
    imagen: "img/tododia-frambuesa-pimienta-roja.jpg",
    imagen2: "img/tododia-frambuesa-pimienta-roja2.jpg",
    oferta: false,
    destacado: true,
    stock: 4
},
{
    id: 82,
    codigo: "Nat0014",
    nombre: "Tododia Hoja de Limón y Guanábana",
    descripcion: "Crema hidratante corporal con notas cítricas y frutales que aportan una sensación refrescante mientras nutre intensamente la piel.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "400 ml",
    precio: 20000,
    imagen: "img/tododia-hoja-limon-guanabana.jpg",
    imagen2: "img/tododia-hoja-limon-guanabana2.jpg",
    oferta: false,
    destacado: true,
    stock: 2
},
{
    id: 83,
    codigo: "Nat0014",
    nombre: "Tododia Limón Siciliano y Flor de Gardenia",
    descripcion: "Crema hidratante corporal con una fragancia fresca y luminosa de limón siciliano y flor de gardenia. Hidrata, suaviza y perfuma la piel durante todo el día.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "400 ml",
    precio: 20000,
    imagen: "img/tododia-limon-siciliano-gardenia.jpg",
    imagen2: "img/tododia-limon-siciliano-gardenia2.jpg",
    oferta: false,
    destacado: true,
    stock: 7
},
{
    id: 84,
    codigo: "Nat0014",
    nombre: "Tododia Ciruela y Flor de Vainilla",
    descripcion: "Crema hidratante corporal con una combinación cálida y envolvente de ciruela y flor de vainilla. Proporciona hidratación profunda y una piel sedosa.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "400 ml",
    precio: 20000,
    imagen: "img/tododia-ciruela-vainilla.jpg",
    imagen2: "img/tododia-ciruela-vainilla2.jpg",
    oferta: false,
    destacado: true,
    stock: 6
},
{
    id: 85,
    codigo: "Nat0014",
    nombre: "Tododia Ciruela y Flor de Cerezo",
    descripcion: "Crema hidratante corporal con un delicado aroma floral y afrutado que deja la piel intensamente hidratada, suave y perfumada.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "400 ml",
    precio: 20000,
    imagen: "img/tododia-ciruela-cerezo.jpg",
    imagen2: "img/tododia-ciruela-cerezo2.jpg",
    oferta: false,
    destacado: true,
    stock: 4
},
    {
    id: 86,
    codigo: "Nat0014",
    nombre: "Tododia Avellana y Casis",
    descripcion: "Crema hidratante corporal con una deliciosa combinación de avellana y casis. Su fórmula nutre profundamente la piel, dejándola suave, perfumada e hidratada durante 48 horas.",
    categoria: "Tododia",
    subcategoria:"Hidratantes",
    subcategoria3:"400 ml",
    precio: 20000,
    imagen: "img/tododia-avellana-casis.jpg",
    imagen2: "img/tododia-avellana-casis2.jpg",
    oferta: false,
    destacado: true,
    stock: 2
},
{
    id: 87,
    codigo: "Nat0014",
    nombre: "Tododia Nuez Pecán y Cacao",
    descripcion: "Crema hidratante corporal enriquecida con manteca de cacao y nuez pecán. Hidrata intensamente, mejora la elasticidad de la piel y deja un aroma cálido y envolvente.",
    categoria: "Tododia",
    subcategoria:"Hidratantes",
    subcategoria3:"400 ml",
    precio: 20000,
    imagen: "img/tododia-nuez-pecan-cacao.jpg",
    imagen2: "img/tododia-nuez-pecan-cacao2.jpg",
    oferta: false,
    destacado: true,
    stock: 5
},
{
    id: 88,
    codigo: "Nat0014",
    nombre: "Tododia Flor de Lis",
    descripcion: "Crema hidratante corporal con la elegancia de la Flor de Lis. Su textura cremosa proporciona hidratación profunda y deja la piel delicadamente perfumada.",
    categoria: "Tododia",
    subcategoria:"Hidratantes",
    subcategoria3:"400 ml",
    precio: 20000,
    imagen: "img/tododia-flor-lis.jpg",
    imagen2: "img/tododia-flor-lis2.jpg",
    oferta: false,
    destacado: true,
    stock: 3
},
{
    id: 89,
    codigo: "Nat0014",
    nombre: "Tododia Flor de Durazno y Jazmín",
    descripcion: "Crema hidratante corporal con una combinación floral delicada de flor de durazno y jazmín. Brinda nutrición intensa y una sensación de frescura durante todo el día.",
    categoria: "Tododia",
    subcategoria:"Hidratantes",
    subcategoria3:"400 ml",
    precio: 20000,
    imagen: "img/tododia-flor-durazno-jazmin.jpg",
    imagen2: "img/tododia-flor-durazno-jazmin2.jpg",
    oferta: false,
    destacado: true,
    stock: 4
},
{
    id: 90,
    codigo: "Nat0014",
    nombre: "Tododia Mango Rosa y Agua de Coco",
    descripcion: "Crema hidratante corporal con una refrescante combinación tropical de mango rosa y agua de coco. Deja la piel suave, luminosa y con un aroma irresistible.",
    categoria: "Tododia",
    subcategoria:"Hidratantes",
    subcategoria3:"400 ml",
    precio: 20000,
    imagen: "img/tododia-mango-rosa-coco.jpg",
    imagen2: "img/tododia-mango-rosa-coco2.jpg",
    oferta: false,
    destacado: true,
    stock: 2
},
{
    id: 91,
    codigo: "Nat0014",
    nombre: "Tododia Flor de Jengibre y Tangerina",
    descripcion: "Crema hidratante corporal con notas cítricas y especiadas de flor de jengibre y tangerina. Nutre profundamente y aporta una agradable sensación revitalizante.",
    categoria: "Tododia",
    subcategoria:"Hidratantes",
    subcategoria3:"400 ml",
    precio: 20000,
    imagen: "img/tododia-jengibre-tangerina.jpg",
    imagen2: "img/tododia-jengibre-tangerina2.jpg",
    oferta: false,
    destacado: true,
    stock: 2
},
{
    id: 92,
    codigo: "Nat0014",
    nombre: "Tododia Acerola y Hibisco",
    descripcion: "Crema hidratante corporal con acerola e hibisco. Su fórmula combina hidratación prolongada con una fragancia fresca, frutal y vibrante.",
    categoria: "Tododia",
    subcategoria:"Hidratantes",
    subcategoria3:"400 ml",
    precio: 20000,
    imagen: "img/tododia-acerola-hibisco.jpg",
    imagen2: "img/tododia-acerola-hibisco2.jpg",
    oferta: false,
    destacado: true,
    stock: 6
},
{
    id: 93,
    codigo: "Nat0014",
    nombre: "Tododia Té de Manzanilla y Lavanda",
    descripcion: "Crema hidratante corporal con té de manzanilla y lavanda. Su fragancia suave brinda una agradable sensación de bienestar mientras hidrata profundamente la piel.",
    categoria: "Tododia",
    subcategoria:"Hidratantes",
    subcategoria3:"400 ml",
    precio: 20000,
    imagen: "img/tododia-manzanilla-lavanda.jpg",
    imagen2: "img/tododia-manzanilla-lavanda2.jpg",
    oferta: false,
    destacado: true,
    stock: 3
},
{
    id: 94,
    codigo: "Nat0014",
    nombre: "Tododia Algodón",
    descripcion: "Crema hidratante corporal Tododia Algodón con una fragancia suave y confortable. Nutre profundamente la piel y proporciona una hidratación prolongada para toda la familia.",
    categoria: "Tododia",
    subcategoria:"Hidratantes",
    subcategoria3:"400 ml",
    precio: 20000,
    imagen: "img/tododia-algodon.jpg",
    imagen2: "img/tododia-algodon2.jpg",
    oferta: false,
    destacado: true,
    stock: 8
},
    {
    id: 90,
    codigo: "Nat0015",
    nombre: "Tododia Flor de Lis",
    descripcion: "Crema hidratante corporal Flor de Lis 200 ml. Nutre profundamente la piel, proporcionando hidratación prolongada, suavidad y un delicado perfume floral.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "200 ml",
    precio: 20000,
    imagen: "img/tododia-flor-de-lis200.jpg",
    oferta: false,
    destacado: true,
    stock: 2
},
{
    id: 91,
    codigo: "Nat0015",
    nombre: "Tododia Ciruela y Flor de Vainilla",
    descripcion: "Crema hidratante corporal Ciruela y Flor de Vainilla 200 ml. Deja la piel intensamente hidratada con una fragancia dulce, envolvente y de larga duración.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "200 ml",
    precio: 20000,
    imagen: "img/tododia-ciruela-vainilla200.jpg",
    oferta: false,
    destacado: true,
    stock: 3
},
{
    id: 92,
    codigo: "Nat0015",
    nombre: "Tododia Macadamia",
    descripcion: "Crema hidratante corporal Macadamia 200 ml. Fórmula nutritiva que hidrata profundamente la piel, aportando elasticidad, suavidad y un aroma cálido.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "200 ml",
    precio: 20000,
    imagen: "img/tododia-macadamia200.jpg",
    oferta: false,
    destacado: true,
    stock: 2
},
{
    id: 93,
    codigo: "Nat0015",
    nombre: "Tododia Algodón",
    descripcion: "Crema hidratante corporal Algodón 200 ml. Proporciona hidratación diaria con una textura ligera y un perfume suave que brinda sensación de confort.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "200 ml",
    precio: 20000,
    imagen: "img/tododia-algodon200.jpg",
    oferta: false,
    destacado: true,
    stock: 2
},
{
    id: 94,
    codigo: "Nat0015",
    nombre: "Tododia Cereza y Avellana",
    descripcion: "Crema hidratante corporal Cereza y Avellana 200 ml. Nutre la piel intensamente mientras deja una fragancia dulce y sofisticada durante todo el día.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "200 ml",
    precio: 20000,
    imagen: "img/tododia-cereza-avellana200.jpg",
    oferta: false,
    destacado: true,
    stock: 1
},
{
    id: 95,
    codigo: "Nat0015",
    nombre: "Tododia Frutas Rojas",
    descripcion: "Crema hidratante corporal Frutas Rojas 200 ml. Hidrata profundamente la piel mientras envuelve el cuerpo con una fragancia frutal fresca y vibrante.",
    categoria: "Tododia",
    subcategoria: "Hidratantes",
    subcategoria3: "200 ml",
    precio: 20000,
    imagen: "img/tododia-frutas-rojas200.jpg",
    oferta: false,
    destacado: true,
    stock: 2
}
];
